# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    #branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Check-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Install requirements
      - name: Install requirements
        run: python3 -m pip install -r requirements.txt

      # make migration and create DB
      - name: Make migration [platform injected]
        run: python3 manage.py makemigrations
      - name: Create DB [platform injected]
        run: python3 manage.py migrate

      # Seed DB
      - name: Seed DB [platform injected]
        run: python3 seed.py
          
